name: 申请添加网站
description: 申请添加博客到中文博客列表导航
title: "申请收录："
labels: 
assignees:
  - MYXXTS
body:
  - type: markdown
    attributes:
      value: |
        感谢你可以百忙之中抽出时间提交网站。
  - type: input
    id: name
    attributes:
      label: 网站名称
      description: 我们会把网站名称显示在导航中，并作为博客搜索的依据。
      placeholder: ex. 阮一峰的博客
    validations:
      required: true
  - type: input
    id: url
    attributes:
      label: 网站地址
      description: 我们会把网站地址显示在导航中，并作为博客搜索的依据。
      placeholder: ex. https://juantu.cn/
    validations:
      required: true
  - type: input
    id: feed
    attributes:
      label: 网站订阅地址
      description: 我们不会把网站订阅地址显示在导航中，不会将其作为博客搜索的依据。
      placeholder: ex. https://juantu.cn/feed/
    validations:
      required: false
  - type: textarea
    id: sign
    attributes:
      label: 网站一句话介绍
      description: 我们不会将其作为搜索依据。如果你不填，我们会从页面中挑选（很有可能是不准确的）。
      placeholder: 
    validations:
      required: false
      
