blank_issues_enabled: false
contact_links:
  - name: 中文博客列表导航文档
    url: https://github.com/zh-blogs/zh-blogs-documentation
    about: 您可以在这里找到这个项目的一些文档。
  - name: 向中文博客列表导航提交网站
    url: https://zhblogs.ohyee.cc/manager/join
    about: 您可以在这里向我们提交网站。
